name: Auto PR

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'hotfix/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          title: ${{ github.ref_name }}
          body: |
            PR auto-générée depuis la branche `${{ github.ref_name }}`.
          draft: false
